repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  # Custom hook to check for a valid email format
  - repo: local
    hooks:
      - id: validate-email-format
        name: Validate Email Format
        entry: python -c "import re, sys; email = sys.args[1]; sys.exit(0)  if re.match(r'^[\w\.-]+@[\w\.-]+\.[a-z]{2,}$', email) else sys.exit(1)"
        language: system
        args: ["sadichhya@fusemachines.com"]
